"""Self-contained HTML report (Jinja2 + inline Plotly; no external requests)."""

from __future__ import annotations

from typing import Any

import yaml
from jinja2 import Environment, PackageLoader, select_autoescape
from markupsafe import Markup, escape

from ..config import Config
from ..results import CheckResult, RunResult
from . import plots

_GROUPS = [
    ("forward", "Forward primer"),
    ("reverse", "Reverse primer"),
    ("probe", "Probe"),
    ("pair", "Primer pair"),
    ("amplicon", "Amplicon"),
]

VERDICT_MEANING = {
    "PASS": "Every evaluated check passed and every required analysis was run.",
    "WARN": "No check failed, but at least one raised a warning. Review the findings.",
    "FAIL": "At least one check failed. See the findings below.",
    "INCOMPLETE": (
        "Required analyses were not evaluated, so this result is not a pass. "
        "Evidence that is missing never counts as a PASS."
    ),
}


def _seq_html(seq: str, tail: int = 5) -> Markup:
    """5'-…-3' with the last ``tail`` nt (the 3' end) emphasised."""
    s = str(escape(seq))
    if len(s) > tail:
        s = f'{s[:-tail]}<b class="tail">{s[-tail:]}</b>'
    return Markup(f'<span class="seq">5′-{s}-3′</span>')  # noqa: S704 - content escaped above


def _tm(value: float | None) -> str:
    if value is None:
        return "none"
    return "< 0" if value < 0 else f"{value:.1f}"


def _dg(value: float | None) -> str:
    return "" if value is None else f"{value:+.2f}"


def _environment() -> Environment:
    env = Environment(
        loader=PackageLoader("qpcr_assay_check.report", "templates"),
        autoescape=select_autoescape(["html", "j2"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["seq_html"] = _seq_html
    env.filters["tm"] = _tm
    env.filters["dg"] = _dg
    return env


def _plotly_js() -> str:
    import plotly.offline as po

    return po.get_plotlyjs()


def render_report(result: RunResult, cfg: Config) -> str:
    """Render the evaluation record as one self-contained HTML document."""
    groups: list[tuple[str, list[CheckResult]]] = []
    for key, title in _GROUPS:
        items = [c for c in result.oligo_qc.checks if c.subject == key]
        if items:
            groups.append((title, items))

    charts: list[dict[str, Any]] = []
    if cfg.report.include_charts:
        html = plots.tm_chart(result, cfg)
        if html:
            charts.append(
                {
                    "title": "Melting temperatures",
                    "html": Markup(html),  # noqa: S704 - generated by Plotly from numeric data
                    "caption": (
                        "Bars show nearest-neighbour Tm (range bars for degenerate oligos). "
                        "The shaded band is the primer PASS range; the dashed line is the "
                        "annealing temperature."
                    ),
                }
            )

    template = _environment().get_template("report.html.j2")
    return template.render(
        r=result,
        qc=result.oligo_qc,
        assay=result.assay,
        groups=groups,
        charts=charts,
        plotly_js=Markup(_plotly_js()) if charts else "",  # noqa: S704 - bundled library
        config_yaml=yaml.safe_dump(result.config, sort_keys=False, allow_unicode=True),
        verdict_meaning=VERDICT_MEANING[result.overall.verdict.value],
    )
