#!/usr/bin/env python3
"""Write the generated parts of the knowledge bundle in docs/knowledge/ (OKF v0.2).

The bundle follows the Open Knowledge Format v0.2
(https://github.com/GoogleCloudPlatform/open-knowledge-format, SPEC.md): markdown files with
YAML frontmatter. Most concepts are written by hand; these parts are generated so they cannot
drift from their sources:

- ``settings/<section>.md``: one concept per top-level section of the packaged
  ``default_config.yaml``, the section copied verbatim with its comments;
- ``releases/v<version>.md``: one concept per released version in ``CHANGELOG.md``, with the
  release summary and the titles of its entries;
- ``log.md``: the bundle's update history, one line per entry of ``docs/PROGRESS.md``;
- ``index.md`` in every directory: the concepts there, with their frontmatter description.

    python scripts/build_knowledge.py          # write
    python scripts/build_knowledge.py --check  # exit 1 when a generated file is out of date

No network access; reads only files in this repository.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

log = logging.getLogger("build_knowledge")

ROOT = Path(__file__).resolve().parent.parent
BUNDLE = ROOT / "docs" / "knowledge"
CONFIG = ROOT / "src" / "qpcr_assay_check" / "data" / "default_config.yaml"
CHANGELOG = ROOT / "CHANGELOG.md"
PROGRESS = ROOT / "docs" / "PROGRESS.md"
OKF_VERSION = "0.2"
ACTOR = "process:build_knowledge"
GENERATED_NOTE = "Generated by `scripts/build_knowledge.py` from {src}; do not edit by hand."
RESERVED = {"index.md", "log.md"}

# Folder order and descriptions for the root index (folders not listed come last, unsorted).
FOLDERS: dict[str, str] = {
    "rules": "How a primer or probe site is graded and how a genome counts, rule by rule",
    "sources": "Papers, reviews and NCBI documentation the rules and facts rest on",
    "decisions": "The user's decisions, dated, with what they changed",
    "assays": "The example assays: where the sequences come from and what was checked",
    "runs": "Live runs the user made and their key numbers",
    "ncbi": "NCBI behaviour checked against current documentation or measured live",
    "components": "What each part of the code does, with links to the source",
    "open": "Open items: review suggestions not taken up, checks still to do",
    "settings": "The default configuration, section by section (generated)",
    "releases": "Released versions (generated from CHANGELOG.md)",
}


@dataclass(frozen=True)
class Concept:
    """One concept document: its file name, title and description."""

    name: str
    title: str
    description: str


def rel(target: Path, start: Path) -> str:
    """``target`` relative to the directory ``start``, with forward slashes."""
    import os

    return Path(os.path.relpath(target, start)).as_posix()


def frontmatter(text: str) -> dict | None:
    """The YAML frontmatter of a markdown text, or None when it has none."""
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    data = yaml.safe_load(text[4:end])
    return data if isinstance(data, dict) else None


def _yaml_value(value: str) -> str:
    """A single-line YAML string, quoted only when needed."""
    dumped = yaml.safe_dump(value, default_flow_style=True, allow_unicode=True, width=1000)
    return dumped.strip().removesuffix("...").strip()


def document(meta: list[tuple[str, str]], body: str) -> str:
    """A concept document from (key, already-formatted YAML value) pairs and a body."""
    head = "\n".join(f"{k}:{v}" if v.startswith("\n") else f"{k}: {v}" for k, v in meta)
    return f"---\n{head}\n---\n\n{body.rstrip()}\n"


# ---------------------------------------------------------------- settings


def config_sections(text: str) -> list[tuple[str, str]]:
    """The top-level sections of the default configuration as (key, verbatim text)."""
    lines = text.splitlines()
    starts = [i for i, line in enumerate(lines) if re.match(r"^[a-z_]+:", line)]
    out = []
    for n, i in enumerate(starts):
        end = starts[n + 1] if n + 1 < len(starts) else len(lines)
        key = lines[i].split(":", 1)[0]
        if key == "schema_version":
            continue
        block = "\n".join(lines[i:end]).rstrip()
        out.append((key, block))
    return out


def settings_files() -> dict[Path, str]:
    """settings/<section>.md for each section of the default configuration."""
    folder = BUNDLE / "settings"
    src = rel(CONFIG, folder)
    files: dict[Path, str] = {}
    for key, block in config_sections(CONFIG.read_text(encoding="utf-8")):
        meta = [
            ("type", "Setting Group"),
            ("title", _yaml_value(f"Settings: {key}")),
            (
                "description",
                _yaml_value(
                    f"Default values of the `{key}` configuration section, "
                    "with the comments that explain them."
                ),
            ),  # fmt: skip
            ("resource", _yaml_value(src)),
            ("tags", f"[settings, {key}]"),
            ("generated", f"{{ by: {ACTOR} }}"),
            (
                "sources",
                f"\n  - id: default-config\n    resource: {src}\n"
                "    title: Packaged default configuration",
            ),  # fmt: skip
        ]
        body = (
            f"# Defaults\n\n{GENERATED_NOTE.format(src='`default_config.yaml`')}\n\n"
            "Every value is a starting point, not an acceptance criterion: each laboratory "
            "reviews it within its own quality system. An assay file can override a value "
            "under `settings:`; a `--config` file overrides the defaults for every run."
            "[^default-config]\n\n"
            f"```yaml\n{block}\n```\n\n"
            "[^default-config]: Packaged default configuration"
        )
        files[folder / f"{key}.md"] = document(meta, body)
    return files


# ---------------------------------------------------------------- releases


@dataclass(frozen=True)
class Release:
    """One released version from the changelog."""

    version: str
    date: str
    summary: str
    groups: list[tuple[str, list[str]]]


def releases(text: str) -> list[Release]:
    """Released versions in CHANGELOG.md, newest first (the Unreleased section is skipped)."""
    out = []
    parts = re.split(r"^## \[", text, flags=re.M)[1:]
    for part in parts:
        head, _, rest = part.partition("\n")
        m = re.match(r"(\d+\.\d+\.\d+)\] - (\d{4}-\d{2}-\d{2})", head)
        if not m:
            continue
        summary_lines = []
        for line in rest.splitlines():
            if line.startswith("### "):
                break
            summary_lines.append(line)
        summary = " ".join(x.strip() for x in summary_lines if x.strip())
        groups: list[tuple[str, list[str]]] = []
        for g in re.split(r"^### ", rest, flags=re.M)[1:]:
            name, _, items = g.partition("\n")
            titles = re.findall(r"^- \*\*(.+?)\*\*", items, flags=re.M)
            groups.append((name.strip(), titles))
        out.append(Release(m.group(1), m.group(2), summary, groups))
    return out


def release_files() -> dict[Path, str]:
    """releases/v<version>.md for each released version."""
    folder = BUNDLE / "releases"
    src = rel(CHANGELOG, folder)
    files: dict[Path, str] = {}
    for r in releases(CHANGELOG.read_text(encoding="utf-8")):
        first = r.summary.split(". ")[0].rstrip(".") if r.summary else ""
        description = first + "." if first else f"Release {r.version} of {r.date}."
        meta = [
            ("type", "Release"),
            ("title", _yaml_value(f"v{r.version} ({r.date})")),
            ("description", _yaml_value(description)),
            (
                "resource",
                _yaml_value(f"https://github.com/zmeel/qpcr-assay-check/releases/tag/v{r.version}"),
            ),  # fmt: skip
            ("tags", "[release]"),
            ("generated", f"{{ by: {ACTOR} }}"),
            ("sources", f"\n  - id: changelog\n    resource: {src}\n    title: CHANGELOG.md"),
        ]
        body = [f"# Release v{r.version}\n", GENERATED_NOTE.format(src="`CHANGELOG.md`"), ""]
        body.append(f"Released {r.date}; annotated tag `v{r.version}`.[^changelog]\n")
        if r.summary:
            body.append(r.summary + "\n")
        for name, titles in r.groups:
            if not titles:
                body.append(f"## {name}\n\nSee the changelog.\n")
                continue
            body.append(f"## {name}\n")
            body.extend(f"- {t}" for t in titles)
            body.append("")
        body.append("[^changelog]: CHANGELOG.md")
        files[folder / f"v{r.version}.md"] = document(meta, "\n".join(body))
    return files


# ---------------------------------------------------------------- log


def progress_entries(text: str) -> list[tuple[str, str]]:
    """(ISO date, title) for each dated entry of PROGRESS.md, in file order (newest first)."""
    out = []
    for line in text.splitlines():
        m = re.match(r"^## (\d{4}-\d{2}-\d{2})\S*(?: \([^)]*\))? — (.+)$", line)
        if m:
            out.append((m.group(1), m.group(2).strip()))
    return out


def log_file() -> dict[Path, str]:
    """log.md: one bullet per PROGRESS.md entry, grouped by date, newest first."""
    entries = progress_entries(PROGRESS.read_text(encoding="utf-8"))
    by_date: dict[str, list[str]] = {}
    for date, title in entries:
        by_date.setdefault(date, []).append(title)
    progress = rel(PROGRESS, BUNDLE)
    lines = [
        "# Update log",
        "",
        f"{GENERATED_NOTE.format(src=f'[PROGRESS.md]({progress})')} PROGRESS.md holds the "
        "full entries; this log names them, newest first.",
        "",
    ]
    for date in sorted(by_date, reverse=True):
        lines.append(f"## {date}")
        lines.extend(f"* **Update**: {t}" for t in by_date[date])
        lines.append("")
    return {BUNDLE / "log.md": "\n".join(lines).rstrip() + "\n"}


# ---------------------------------------------------------------- indexes


def concepts_in(folder: Path, generated: dict[Path, str]) -> list[Concept]:
    """The concept documents directly in ``folder`` (generated ones included), sorted."""
    names = {p.name for p in folder.glob("*.md")} | {
        p.name for p in generated if p.parent == folder
    }
    out = []
    for name in sorted(names - RESERVED):
        path = folder / name
        text = generated.get(path) or path.read_text(encoding="utf-8")
        meta = frontmatter(text) or {}
        title = str(meta.get("title") or name.removesuffix(".md"))
        out.append(Concept(name, title, str(meta.get("description") or "").strip()))
    return out


def _entry(link: str, title: str, description: str) -> str:
    return f"* [{title}]({link})" + (f" - {description}" if description else "")


def index_files(generated: dict[Path, str]) -> dict[Path, str]:
    """index.md for the bundle root and every folder below it."""
    files: dict[Path, str] = {}
    folders = {p for p in BUNDLE.iterdir() if p.is_dir()} | {
        p.parent for p in generated if p.parent != BUNDLE
    }
    for folder in sorted(folders):
        title = folder.name.capitalize()
        lines = [f"# {title}", ""]
        if folder.name in FOLDERS:
            lines += [FOLDERS[folder.name] + ".", ""]
        lines += [_entry(c.name, c.title, c.description) for c in concepts_in(folder, generated)]
        if folder.name == "releases":  # newest first
            entries = [x for x in lines if x.startswith("* ")]
            entries.sort(key=lambda x: [int(n) for n in re.findall(r"v(\d+)\.(\d+)\.(\d+)", x)[0]])
            lines = lines[: len(lines) - len(entries)] + entries[::-1]
        files[folder / "index.md"] = "\n".join(lines).rstrip() + "\n"
    order = list(FOLDERS) + sorted(f.name for f in folders if f.name not in FOLDERS)
    root = [
        "---",
        f'okf_version: "{OKF_VERSION}"',
        "---",
        "",
        "# qpcr-assay-check knowledge bundle",
        "",
    ]
    root += [_entry(c.name, c.title, c.description) for c in concepts_in(BUNDLE, generated)]
    root += ["", "# Folders", ""]
    root += [
        _entry(f"{name}/index.md", name, FOLDERS.get(name, ""))
        for name in order
        if (BUNDLE / name) in folders
    ]
    root += ["", "# History", "", _entry("log.md", "Update log", "every session, newest first")]
    files[BUNDLE / "index.md"] = "\n".join(root) + "\n"
    return files


# ---------------------------------------------------------------- main


def build() -> dict[Path, str]:
    """Every generated file of the bundle and its content."""
    generated = {**settings_files(), **release_files(), **log_file()}
    generated.update(index_files(generated))
    return generated


def main(argv: list[str] | None = None) -> int:
    """Write the generated files, or with --check report the ones out of date."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="only check, write nothing")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    stale = []
    for path, content in sorted(build().items()):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    for path in stale:
        log.info("%s %s", "out of date:" if args.check else "wrote", rel(path, ROOT))
    if args.check and stale:
        log.info("run: python scripts/build_knowledge.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
